apiVersion: 1

# Define data sources for Prometheus
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true
    version: 1
