name: Frontend Build & Deploy

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-build.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install dependencies
        run: npm ci --prefix frontend --legacy-peer-deps
      
      - name: Run linting
        run: npm run lint --prefix frontend
      
      - name: Type check
        run: npm run type-check --prefix frontend
      
      - name: Run tests
        run: npm run test:coverage --prefix frontend
      
      - name: Build for development
        run: npm run build --prefix frontend -- --mode development
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./frontend/coverage/coverage-final.json
        continue-on-error: true
      
      - name: Analyze bundle size
        run: |
          SIZE=$(du -sh frontend/dist | cut -f1)
          echo "Bundle size: $SIZE"
          echo "BUNDLE_SIZE=$SIZE" >> $GITHUB_ENV
      
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Frontend build successful\nBundle size: ${{ env.BUNDLE_SIZE }}'
            })
        continue-on-error: true
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist/
          retention-days: 5

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v2
      
      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: heimdall-frontend:latest
